admin/QavantWeb/Models/Notification.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QavantWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.NotificationsFilters = new HashSet<NotificationsFilter>();
        }
    
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte SectionId { get; set; }
        public Nullable<int> BenefitId { get; set; }
        public Nullable<int> NewsId { get; set; }
        public string Status { get; set; }
        public string CreationUserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> FormsId { get; set; }
        public Nullable<int> InfoUtilId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Benefit Benefit { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Form Form { get; set; }
        public virtual InfoUtil InfoUtil { get; set; }
        public virtual Noticia Noticia { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationsFilter> NotificationsFilters { get; set; }
    }
}

admin/QavantWeb/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QavantWeb.Models;
using System.Net.Http;
using System.Text;
using System.Web.Configuration;
using Microsoft.AspNet.Identity;
using System.IO;
using Newtonsoft.Json;
using QavantWeb.Common;
using QavantWeb.Infrastructure.Notifications;

namespace QavantWeb.Controllers
{
    public class NotificationsController : Controller
    {
        private QavantEntities db = new QavantEntities();
        private int empresaId = SecurityHelpers.getEmpresaId();
        private readonly INotification _notification;

        public NotificationsController() : this(new FirebaseNotification()) { }

        public NotificationsController(INotification notification)
        {
            _notification = notification;
        }

        // GET: Notifications
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            var notifications = db.Notifications
                                  //.Include(n => n.Benefit)
                                  //.Include(n => n.Noticia)
                                  //.Include(n => n.Section)
                                  .Where(w => w.EmpresaId == empresaId)
                                  .OrderByDescending(x => x.CreationDate);

            return View(notifications.ToList());
        }

        // GET: Notifications/Details/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notification notification = db.Notifications.Where(w => w.EmpresaId == empresaId).FirstOrDefault(f=>f.Id==id);
            if (notification == null)
            {
                return HttpNotFound();
            }
            return View(notification);
        }

        // GET: Notifications/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            ViewBag.BenefitId = new SelectList(db.Benefits.Where(w => w.EmpresaId == empresaId).Where(o => o.From <= DateTime.Today && o.To >= DateTime.Today).Where(o => o.Enabled).OrderBy(o => o.Title), "Id", "Title");
            ViewBag.NewsId = new SelectList(db.Noticias.Where(w => w.EmpresaId == empresaId).OrderBy(o => o.Titulo).Where(o => o.Habilitada), "Id", "Titulo");
            ViewBag.CourseId = new SelectList(db.Courses.Where(w => w.EmpresaId == empresaId).Where(o => o.From <= DateTime.Today && o.To >= DateTime.Today).Where(o => o.Enabled).OrderBy(o => o.Title), "Id", "Title");
            ViewBag.SurveysId = new SelectList(db.Forms.Where(w => w.EmpresaId == empresaId).Where(o => o.DateFrom <= DateTime.Today && o.DateTo >= DateTime.Today).Where(o => o.Enabled && o.FormTypeId == (byte)Models.Enums.FormsTypes.Encuesta).OrderBy(o => o.Title), "Id", "Title");
            ViewBag.FormsId = new SelectList(db.Forms.Where(w => w.EmpresaId == empresaId).Where(o => o.DateFrom <= DateTime.Today && o.DateTo >= DateTime.Today).Where(o => o.Enabled && o.FormTypeId == (byte)Models.Enums.FormsTypes.Formulario).OrderBy(o => o.Title), "Id", "Title");
            ViewBag.InfoUtilId = new SelectList(db.InfoUtils.Where(w => w.EmpresaId == empresaId).OrderBy(o => o.Titulo).Where(o => o.Habilitado == true), "Id", "Titulo");
            ViewBag.GaleriaId = new SelectList(db.Galerias.Where(w => w.EmpresaId == empresaId).OrderBy(o => o.Titulo).Where(o => o.Habilitada == true), "Id", "Titulo");

            ViewBag.SectionId = new SelectList(db.Sections.Where(s => s.Enabled == true).OrderBy(o => o.Name), "Id", "Name", "AppLink");
            ViewBag.FilterAreas = new SelectList(db.Areas.Where(w => w.EmpresaId == empresaId).Where(w => w.Habilitada).OrderBy(o => o.Nombre), "Id", "Nombre");
            ViewBag.FilterGroups = new SelectList(db.Groups.Where(w => w.EmpresaId == empresaId).Where(w => w.Enabled).OrderBy(o => o.Name), "Id", "Name");
            List<Section> lista = db.Sections.ToList();
            ViewBag.lista = lista;
            return View();
        }

        // POST: Notifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create(Notification notification)
        {
            notification.CreationUserId = User.Identity.GetUserId();
            notification.CreationDate = DateTime.Now;
            Section section = db.Sections.Where(x => x.Id == notification.SectionId).FirstOrDefault();


            if (ModelState.IsValid)
            {
                notification.Status = "NO ENVIADO";
                notification.EmpresaId = empresaId;
                db.Notifications.Add(notification);
                db.SaveChanges();

                //Envio notificaciones
                //TRAER LOS TOKENS A ENVIAR
                List<Device> devs = new List<Device>();
                string tokens = "";

                List<NotificationsFilter> lsFilters = db.NotificationsFilters.Where(w => w.NotificationId == notification.Id).ToList(); //tendría que de Segmentación  get_filtros 
                if (lsFilters.Count == 0)
                    devs.AddRange(db.Devices.Include(i => i.User).Where(w => w.User.EmpresaId == empresaId).Where(w => w.User.Enable && w.User.Active).ToList());
                else
                {
                    List<int> lsUsersToAdd = new List<int>();
                    foreach (NotificationsFilter oFilter in lsFilters)
                    {
                        switch (oFilter.FilteType)
                        {
                            case "GROUP":
                                lsUsersToAdd.AddRange(db.Users
                                                            .Include(i => i.UsersGroups)
                                                            .ToList()
                                                            .Where(w => w.EmpresaId == empresaId)
                                                            .Where(w => w.UsersGroups.Any(a => a.GroupId.ToString() == oFilter.FilterValue))
                                                            .Where(w => !lsUsersToAdd.Contains(w.Id))
                                                            .Select(s => s.Id));
                                break;
                            case "AREA":
                                lsUsersToAdd.AddRange(db.Users
                                                            .Include(i => i.UsersGroups)
                                                            .ToList()
                                                            .Where(w => w.EmpresaId == empresaId)
                                                            .Where(w => w.Area_Id != null && w.Area_Id.ToString() == oFilter.FilterValue)
                                                            .Where(w => !lsUsersToAdd.Contains(w.Id))
                                                            .Select(s => s.Id));
                                break;
                            case "SEX":
                                lsUsersToAdd.AddRange(db.Users
                                                            .Include(i => i.UsersGroups)
                                                            .ToList()
                                                            .Where(w => w.EmpresaId == empresaId)
                                                            .Where(w => !lsUsersToAdd.Contains(w.Id))
                                                            .Select(s => s.Id));
                                break;
                        }
                    }
                    devs.AddRange(db.Devices.Include(i => i.User)
                                    .Where(w => w.User.EmpresaId == empresaId)
                                    .Where(w => w.User.Enable && w.User.Active)
                                    .Where(w => lsUsersToAdd.Contains(w.UserId))
                                    .ToList());
                }

                var tokensForNotification = new List<string>();
                foreach (Device d in devs)
                {
                    tokensForNotification.Add(d.TokenNotification);
                }

                if (tokensForNotification.Count > 0)
                {
                    string idSeleccionado = "";
                    if (notification.SectionId == (byte)Models.Enums.SectionsIds.Beneficios &&
                        notification.BenefitId != null)
                    {
                        idSeleccionado = "/" + notification.BenefitId.ToString();
                    }
                    else if (notification.SectionId == (byte)Models.Enums.SectionsIds.Noticias &&
                            notification.NewsId != null)
                    {
                        idSeleccionado = "/" + notification.NewsId.ToString();
                    }
                    else if (notification.SectionId == (byte)Models.Enums.SectionsIds.Cursos &&
                            notification.CourseId != null)
                    {
                        idSeleccionado = "/" + notification.CourseId.ToString();
                    }
                    else if (notification.SectionId == (byte)Models.Enums.SectionsIds.InfoUtil &&
                        notification.InfoUtilId != null)
                    {
                        idSeleccionado = "/" + notification.InfoUtilId.ToString();
                    }
                    else if (notification.SectionId == (byte)Models.Enums.SectionsIds.Encuestas &&
                            notification.SurveysId != null)
                    {

admin/QavantWeb/Views/Notifications/Create.cshtml
@model QavantWeb.Models.Notification
@{
    ViewBag.Title = "Create";
}
<h2> Crear</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Notificación</h4>
    <hr />
    <!-- Alert -->
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="alert alert-warning alert-dismissible" id="myAlert">
        <a href="#" class="close">&times;</a>
        <p id="msgAlert"></p>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header navbar-inverse">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" style="color:white">ATENCIÓN:</h4>
                </div>
                <div class="modal-body">
                    <p>No hay filtros ingresados. La notificación se enviará a todos los usuarios del sistema. ¿Desea continuar?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"> NO </button>
                    <button type="submit" class="btn btn-primary"> SI </button>
                </div>
            </div>

        </div>
    </div>

    <div class="form-group">
        <div class="control-label texto-label-left col-md-2"><b>Título</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control titulo" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="control-label texto-label-left col-md-2"><b>Mensaje</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control subtitulo", rows = "5" } })
            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="control-label texto-label-left col-md-2"><b>Sección</b></div>
        <div class="col-md-10">
            @Html.DropDownList("SectionId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="BeneficioGroup">
        <div class="control-label texto-label-left col-md-2"><b>Producto</b></div>
        <div class="col-md-10">
            @Html.DropDownList("BenefitId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BenefitId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="NoticiaGroup">
        <div class="control-label texto-label-left col-md-2"><b>Noticia</b></div>
        <div class="col-md-10">
            @Html.DropDownList("NewsId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NewsId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="CursoGroup">
        <div class="control-label texto-label-left col-md-2"><b>Curso</b></div>
        <div class="col-md-10">
            @Html.DropDownList("CourseId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="EncuestaGroup">
        <div class="control-label texto-label-left col-md-2"><b>Encuesta</b></div>
        <div class="col-md-10">
            @Html.DropDownList("SurveysId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SurveysId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="FormularioGroup">
        <div class="control-label texto-label-left col-md-2"><b>Formulario</b></div>
        <div class="col-md-10">
            @Html.DropDownList("FormsId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FormsId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="InfoUtilGroup">
        <div class="control-label texto-label-left col-md-2"><b>Información útil</b></div>
        <div class="col-md-10">
            @Html.DropDownList("InfoUtilId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.InfoUtilId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="GaleriaGroup">
        <div class="control-label texto-label-left col-md-2"><b>Galerías</b></div>
        <div class="col-md-10">
            @Html.DropDownList("GaleriaId", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GaleriaId, "", new { @class = "text-danger" })
        </div>
    </div>


    <hr />
    <div class="panel panel-default" id="pnlFiltros">
        <div class="panel-heading">
            <h3 class="panel-title">Filtros</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-5 row">
                    <div class="col-md-5"><label>Tipo de Filtro:</label></div>
                    <div class="col-md-7">
                        <select id="FilterType" class="form-control">
                            <option value="GROUP">Grupos</option>
                            <option value="AREA">Áreas</option>
                            <option value="SEX">Géneros</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-5 row">
                    <div class=" filterOptions" id="FilterAreas_group">
                        <div class="col-md-2"><label>Áreas:</label></div>
                        <div class="col-md-10">
                            @Html.DropDownList("FilterAreas", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class=" filterOptions" id="FilterGroups_group">
                        <div class="col-md-2"><label>Grupos:</label></div>
                        <div class="col-md-10">
                            @Html.DropDownList("FilterGroups", null, "Seleccionar", htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class=" filterOptions" id="FilterGender_group">
                        <div class="col-md-2"><label>Género:</label></div>
                        <div class="col-md-10">
                            <select id="FilterGenders" class="form-control">
                                <option value="M">Masculinos</option>
                                <option value="F">Femeninos</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-md-2">
                    <button type="button" class="btn btn-primary col-md-12" id="btn_FilterAdd">Agregar</button>
                    <input type="hidden" id="hdn_Edit" value="0" />
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <table id="tbl_Filters" class="table table-hover display compact stripe">
                        <thead>
                            <tr>
                                <td class="col-md-3">Tipo de Filtro</td>
                                <td class="col-md-4">Valor</td>
                                <td class="col-md-1"></td>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.NotificationsFilters != null)
                            {
                                for (int i = 0; i < Model.NotificationsFilters.Count(); i++)
                                {
                                    <tr id="tr_fil_@i" style="@if(Model.NotificationsFilters.ToList()[i].Action=="B") { <text>display:none</text> }">
                                        <td>@Model.NotificationsFilters.ToList()[i].FilteType</td>
                                        <td>@Model.NotificationsFilters.ToList()[i].Description</td>
                                        <td>
                                            <button id="btn_FilterDelete" actionid="@i" type="button" class="btn btn-default btnDelete"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                            <input type="hidden" id="hdn_NotificationsFiltersAction_@i" name="NotificationsFilters[@i].Action" value="@Model.NotificationsFilters.ToList()[i].Action" />
                                            <input type="hidden" id="hdn_NotificationsFiltersId_@i" name="NotificationsFilters[@i].Id" value="@Model.NotificationsFilters.ToList()[i].Id" />
                                            <input type="hidden" id="hdn_NotificationsFiltersNotificationId_@i" name="NotificationsFilters[@i].NotificationId" value="@Model.NotificationsFilters.ToList()[i].NotificationId" />
                                            <input type="hidden" id="hdn_NotificationsFiltersFilteType_@i" name="NotificationsFilters[@i].FilteType" value="@Model.NotificationsFilters.ToList()[i].FilteType" />
                                            <input type="hidden" id="hdn_NotificationsFiltersFilterValue_@i" name="NotificationsFilters[@i].FilterValue" value="@Model.NotificationsFilters.ToList()[i].FilterValue" />
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class=" form-group col-md-12">
        <a href="@Url.Action("Index", "Notifications")" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
        <button type="submit" class="btn btn-primary" onclick="javascript: return confirmMessages();"> Enviar </button>
    </div>

</div>
}
@section Scripts {
    <!-- Print. -->
    <script type="text/javascript" src="~/Scripts/Pages/notifications.js?v=2"></script>
}

admin/QavantWeb/Views/Notifications/Details.cshtml
@model QavantWeb.Models.Notification
@{
    ViewBag.Title = "Details";
}
<h2>Detalles</h2>
<div>
    <h4>Notificación</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.BenefitId != null)
        {
            <dt>
                Producto
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Benefit.Title)
            </dd>

        }
        @if (Model.NewsId != null)
        {
            <dt>
                Noticia
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Noticia.Titulo)
            </dd>
        }
        @if (Model.CourseId != null)
        {
            <dt>
                Curso
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cours.Title)
            </dd>
        }
        <dt>
            Sección
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Section.Name)
        </dd>
        <dt>
            Título
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            Mensaje
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt>
            Fecha
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
</div>
@*<p>    
    @Html.ActionLink("Volver a la lista", "Index")
</p>*@


<hr />
<div class="form-group">
    <div class="col-md-10">
        <a href="@Url.Action("Index", "Notifications")" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>       
    </div>
</div>

admin/QavantWeb/Views/Notifications/Index.cshtml
@model IEnumerable<QavantWeb.Models.Notification>

@{
    ViewBag.Title = "Index";
}

<h2><i class="fa fa-bell " aria-hidden="true"></i> Notificaciones</h2>


<div style="margin-bottom: 30px">
    <a href="@Url.Action("Create", "Notifications")" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nueva Notificación </a>
</div>

<table id="NotificationsList" class="table hover display compact stripe">
    <thead>
        <tr>
            <th>
                Título
            </th>
            <th>
                Mensaje
            </th>
            <th>
                Fecha
            </th>
            <th>
                Usuario
            </th>
            <th>
                Estado
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.Surname), @Html.DisplayFor(modelItem => item.AspNetUser.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a href="@Url.Action("Details", "Notifications", new { id = item.Id })" class="btn btn-default">Detalles </a>
                @*@Html.ActionLink("Detalles", "Details", new { id=item.Id })*@
            </td>
        </tr>
    }

</table>

<script>
    $(document).ready(function () {
        $.fn.dataTable.moment('DD/MM/YYYY HH:mm:ss');
        $('#NotificationsList').DataTable({
            "order": [],
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por página",
                "zeroRecords": "No se encontraron resultados",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Ningún registro disponible",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar:",
                "processing": "Procesando...",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
            buttons: [
                'csv', 'excel', 'pdf'
            ]
        });
    });
</script>