admin/QavantWeb/Models/Establecimiento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QavantWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Establecimiento()
        {
            this.Estudios = new HashSet<Estudio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int EmpresaId { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudio> Estudios { get; set; }
    }
}

admin/QavantWeb/Controllers/EstablecimientoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QavantWeb.Common;
using QavantWeb.Models;

namespace QavantWeb.Controllers
{
    public class EstablecimientoController : Controller
    {
        private QavantEntities db = new QavantEntities();
        private int empresaId = SecurityHelpers.getEmpresaId();

        // GET: Establecimiento
        public ActionResult Index()
        {
            var establecimientos = db.Establecimientos.Include(e => e.Empresa).Where(w => w.EmpresaId == empresaId);
            return View(establecimientos.ToList());
        }

        // GET: Establecimiento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Establecimiento establecimiento = db.Establecimientos.Find(id);
            if (establecimiento == null)
            {
                return HttpNotFound();
            }
            return View(establecimiento);
        }

        // GET: Establecimiento/Create
        public ActionResult Create()
        {           
            return View();
        }

        // POST: Establecimiento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Establecimiento establecimiento)
        {
            if (ModelState.IsValid)
            {
                establecimiento.EmpresaId = empresaId;
                db.Establecimientos.Add(establecimiento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var establecimientos = db.Establecimientos.Include(e => e.Empresa).Where(w => w.EmpresaId == empresaId);
            return View(establecimientos);
        }

        // GET: Establecimiento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Establecimiento establecimiento = db.Establecimientos.Where(w => w.EmpresaId == empresaId).FirstOrDefault(w => w.Id == id);
            if (establecimiento == null)
            {
                return HttpNotFound();
            }
           
            return View(establecimiento);
        }

        // POST: Establecimiento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Establecimiento establecimiento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(establecimiento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpresaId = new SelectList(db.Empresas, "Id", "Nombre", establecimiento.EmpresaId);
            return View(establecimiento);
        }

        // GET: Establecimiento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Establecimiento establecimiento = db.Establecimientos.Where(w => w.EmpresaId == empresaId).FirstOrDefault(w => w.Id == id);
            if (establecimiento == null)
            {
                return HttpNotFound();
            }
            return View(establecimiento);
        }

        // POST: Establecimiento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Establecimiento establecimiento = db.Establecimientos.Where(w => w.EmpresaId == empresaId).FirstOrDefault(w => w.Id == id);
            if(establecimiento.Estudios.Count > 0)
            {
                ModelState.AddModelError("", "No es posible eliminar el establecimiento. El establecimiento posee usuarios asociados. ");
            }
            else
            {
                db.Establecimientos.Remove(establecimiento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(establecimiento);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

admin/QavantWeb/Views/Establecimiento/Create.cshtml
@model QavantWeb.Models.Establecimiento

@{
    ViewBag.Title = "Create";
}

<h2>Establecimientos</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Crear</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2"><b>Habilitado</b></div>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Habilitado, new { @class = "no-left-margin" })
                </div>
            </div>
        </div>

        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "Establecimiento")" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
                <button type="submit" class="btn btn-primary"> Guardar </button>
            </div>
        </div>

    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

admin/QavantWeb/Views/Establecimiento/Delete.cshtml
@model QavantWeb.Models.Establecimiento

@{
    ViewBag.Title = "Delete";
}
<h2>Eliminar</h2>
<h3>¿Seguro que desea eliminar este establecimiento?</h3>
<div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Habilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habilitado)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <a href="@Url.Action("Index", "Establecimiento", new { id = Model.Id })" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash " aria-hidden="true"></span> Eliminar </button>
    }
</div>

admin/QavantWeb/Views/Establecimiento/Details.cshtml
@model QavantWeb.Models.Establecimiento

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Establecimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Habilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habilitado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

admin/QavantWeb/Views/Establecimiento/Edit.cshtml
@model QavantWeb.Models.Establecimiento

@{
    ViewBag.Title = "Edit";
}

<h2>Establecimiento</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.EmpresaId)
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2"><b>Habilitado</b></div>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Habilitado, new { @class = "no-left-margin", id = "chbHabilitado" })
                    <input type="hidden" id="checkId" value="@Model.Estudios.Count()" />
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("_ConfirmModal", "Este establecimiento posee usuarios asociados. ¿Desea continuar de todos modos?")
    <hr />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("Index", "Establecimiento")" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
            <button type="submit" class="btn btn-primary"> Guardar </button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Pages/disable-warning.js"></script>
}

admin/QavantWeb/Views/Establecimiento/Index.cshtml
@model IEnumerable<QavantWeb.Models.Establecimiento>

@{
    ViewBag.Title = "Index";
}

<h2><i class="fa fa-building " aria-hidden="true"></i> Establecimientos</h2>
<div style="margin-bottom: 30px">
    <a href="@Url.Action("Create", "Establecimiento")" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo Establecimiento</a>
</div>

<div class="col-xs-12">

    <table id="EstableList" class="table hover display compact stripe">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Habilitado)
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @if (item.Habilitado)
                    {
                        <i class="fa fa-check-circle fa-2x fa-fw" style="color: #5cb85c;" aria-hidden="true"></i>
                    }
                    else
                    {
                        <i class="fa fa-times-circle fa-2x fa-fw" style="color: #d9534f" aria-hidden="true"></i>
                    }
                </td>

                <td style="text-align: right;">
                    <a href="@Url.Action("Edit", "Establecimiento", new { id = item.Id })" class="btn btn-primary"><span class="glyphicon glyphicon-pencil disabled" aria-hidden="true"></span></a>
                    <a href="@Url.Action("Delete", "Establecimiento", new { id = item.Id })" class="btn btn-danger"><span class="glyphicon glyphicon-trash " aria-hidden="true"></span></a>
                </td>
            </tr>
        }
    </table>
</div>
<script>
    $(document).ready(function () {
        $('#EstableList').DataTable({
            "order": [[0, "asc"]],
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por página",
                "zeroRecords": "No se encontraron resultados",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Ningún registro disponible",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar:",
                "processing": "Procesando...",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Siguiente",
                    "previous": "Anterior"
                },
            },
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>