admin/QavantWeb/Models/Categoria.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QavantWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.BenefitCategories = new HashSet<BenefitCategory>();
            this.Categorias1 = new HashSet<Categoria>();
            this.Courses = new HashSet<Cours>();
            this.Documents = new HashSet<Document>();
            this.Forms = new HashSet<Form>();
            this.Galerias = new HashSet<Galeria>();
            this.InfoUtils = new HashSet<InfoUtil>();
        }
    
        public int Id { get; set; }
        public int ModuloId { get; set; }
        public int EmpresaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> PadreCategoriaId { get; set; }
        public string Imagen { get; set; }
        public bool Habilitada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitCategory> BenefitCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categorias1 { get; set; }
        public virtual Categoria Categoria1 { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form> Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Galeria> Galerias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoUtil> InfoUtils { get; set; }
    }
}

admin/QavantWeb/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using QavantWeb.Models;
using QavantWeb.Common;

namespace QavantWeb.Controllers
{
    public class CategoriasController : Controller
    {

        private QavantEntities db = new QavantEntities();
        private int empresaId = SecurityHelpers.getEmpresaId();

        // GET: Categorias
        public ActionResult Index()
        {
            List<Categoria> lsCat = new List<Categoria>();
            List<Categoria> list = db.Categorias.Where(w => w.EmpresaId == empresaId).Where(w => w.Habilitada).ToList();
            foreach (var item in list)
            {
                switch (item.Modulo.Nemonico)
                {
                    case "INFUT":
                        item.Modulo.Nombre = "Info Útil";
                        break;
                    case "GALER":
                        item.Modulo.Nombre = "Galerías";
                        break;
                }
            }
            Common.FormatterHelpers.CategoriasToTree(list, ref lsCat, null, "", true);

            return View(lsCat);
        }

        // GET: Categorias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Where(w => w.EmpresaId == empresaId).Single(f => f.Id == id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        public JsonResult GetModulos()
        {
            //var modulos = db.Modulos.Where(w => w.UsoEnCategorias).Where(w => w.Empresas.Any(an => an.Id == empresaId)).ToList();
            var modulos = db.Modulos.Where(w => w.UsoEnCategorias).ToList();
            dynamic data = new List<dynamic>();
            foreach (var item in modulos)
            {
                switch (item.Nemonico)
                {
                    case "INFUT":
                        item.Nombre = "Info Útil";
                        break;
                    case "GALER":
                        item.Nombre = "Galerías";
                        break;
                }
                data.Add(new
                {
                    Id = item.Id,
                    Nombre = item.Nombre
                });
            }
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetCategoriasByModulo(int moduloId)
        {
            List<Categoria> lsCat = new List<Categoria>();
            List<Categoria> list = db.Categorias.Where(w => w.EmpresaId == empresaId).Where(c => c.Habilitada && c.ModuloId == moduloId).ToList();
            Common.FormatterHelpers.CategoriasToTree(list, ref lsCat, null, "", true);

            dynamic data = new List<dynamic>();
            foreach (var item in lsCat)
            {
                data.Add(new
                {
                    Id = item.Id,
                    Nombre = item.Nombre
                });
            }
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCategoriaById(int id)
        {
            if (id == 0)
                throw new Exception("Id de categoría no válido.");

            Categoria categoria = db.Categorias.Where(w => w.EmpresaId == empresaId).Single(f => f.Id == id);
            if (categoria == null)
                throw new Exception("Categoría no existente.");

            //recuperamos categorias
            List<Categoria> categoriasAux = new List<Categoria>();
            List<Categoria> list = db.Categorias.Where(w => w.EmpresaId == empresaId).Where(c => c.Habilitada && c.ModuloId == categoria.ModuloId).ToList();
            Common.FormatterHelpers.CategoriasToTree(list, ref categoriasAux, null, "", true);
            dynamic categoriasList = new List<dynamic>();
            foreach (var item in categoriasAux)
            {
                categoriasList.Add(new
                {
                    Id = item.Id,
                    Nombre = item.Nombre
                });
            }

            //recuperamos modulos
            dynamic modulosList = new List<dynamic>();
            var modulos = db.Modulos.Where(w => w.UsoEnCategorias).ToList();
            foreach (var item in modulos)
            {
                switch (item.Nemonico)
                {
                    case "INFUT":
                        item.Nombre = "Info Útil";
                        break;
                    case "GALER":
                        item.Nombre = "Galerías";
                        break;
                }
                modulosList.Add(new
                {
                    Id = item.Id,
                    Nombre = item.Nombre
                });

            }

            return Json(
                new
                {
                    ModuloId = categoria.ModuloId,
                    CategoriaPadreId = (categoria.PadreCategoriaId != null) ? categoria.PadreCategoriaId : 0,
                    CategoriaNombre = categoria.Nombre,
                    Modulos = modulosList,
                    Categorias = categoriasList
                },
                JsonRequestBehavior.AllowGet);
        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Categoria categoria)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (categoria.PadreCategoriaId == 0)
                        categoria.PadreCategoriaId = null;
                    categoria.Habilitada = true;
                    categoria.EmpresaId = empresaId;
                    db.Categorias.Add(categoria);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error en el alta. \n " + ex.Message + " - " + ex.StackTrace + " - " + ex.Source);
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Categoria categoria = db.Categorias.Where(w => w.EmpresaId == empresaId).FirstOrDefault(f => f.Id == id);
            Categoria categoria = db.Categorias.Where(w => w.EmpresaId == empresaId).Single(f => f.Id == id);
            if (categoria == null)
            {
                return HttpNotFound();
            }

            switch (categoria.Modulo.Nemonico)
            {
                case "INFUT":
                    categoria.Modulo.Nombre = "Info Útil";
                    break;
                case "GALER":
                    categoria.Modulo.Nombre = "Galerías";
                    break;
            }

            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categoria categoria)
        {
            //que no sea el padre
            try
            {

                if (categoria.EmpresaId != empresaId)
                {
                    ModelState.AddModelError("", "Error al actualizar el registro.");
                }
                if (categoria.Id == categoria.PadreCategoriaId)
                {
                    ModelState.AddModelError("", "La categoría no puede ser padre de sí misma.");
                }

                if (ModelState.IsValid)
                {
                    if (categoria.PadreCategoriaId == 0)
                        categoria.PadreCategoriaId = null;
                    categoria.Habilitada = true;
                    db.Entry(categoria).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error en el alta. \n " + ex.Message + " - " + ex.StackTrace + " - " + ex.Source);
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Categoria categoria = db.Categorias.Where(w => w.EmpresaId == empresaId).Where(w => w.Habilitada).Single(s => s.Id == id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            switch (categoria.Modulo.Nemonico)
            {
                case "INFUT":
                    categoria.Modulo.Nombre = "Info Útil";
                    break;
                case "GALER":
                    categoria.Modulo.Nombre = "Galerías";
                    break;
            }
            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

admin/QavantWeb/Views/Categorias/Create.cshtml
@model QavantWeb.Models.Categoria

@{
    ViewBag.Title = "Create";
}

<h2>Categoría</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Crear</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="control-label col-md-2"> Módulo </div>
        <div class="col-md-10">
            <select id="modulosDropDownList" class="form-control" name="ModuloId"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"> Nombre </div>
        <div class="col-md-10">
            <input id="nombre" name="Nombre" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"> Padre </div>
        <div class="col-md-10">
            <select id="categoriasDropDownList" class="form-control" name="PadreCategoriaId"></select>
        </div>
    </div>

    <div class="form-group col-md-12">
        <hr />
        <a href="@Url.Action("Index", "Categorias")" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
        <input type="submit" value="Crear" class="btn btn-primary" id="cmdSubmit" />
    </div>
</div>
}




<script>
    $(document).ready(function () {

        //populamos combo "módulos"
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetModulos", "Categorias")',
            dataType: "json",
            success: function (data) {
                $('#modulosDropDownList').html('');
                var options = '';
                options += '<option value="0">Seleccionar</option>';
                for (var i = 0; i < data.length; i++) {
                    options += '<option value="' + data[i].Id + '">' + data[i].Nombre + '</option>';
                }
                $('#modulosDropDownList').append(options); 
            },
            error: function (error) {
                alert(error.StatusText);
            }
        });

        //populamos combo categorias
        $('#modulosDropDownList').on("change", function () {
            var moduloId = $('#modulosDropDownList').val();
            if (moduloId == 0) {
                $('#categoriasDropDownList').html('');
                return;
            }

            var obj = { moduloId: moduloId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCategoriasByModulo", "Categorias")',
                dataType: "json",
                data: obj,
                success: function (data) {
                    $('#categoriasDropDownList').html('');
                    var options = '';
                    options += '<option value="0">Sin Padre</option>';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i].Id + '">' + data[i].Nombre + '</option>';
                    }
                    $('#categoriasDropDownList').append(options); 
                },
                error: function (error) {
                    alert(error.StatusText);
                }
            });
        });

        //validaciones
        $("#cmdSubmit").click(function (event) {
            event.preventDefault();
            if ($('#modulosDropDownList').val() == 0) {
                alert("Seleccione un módulo");
                return;
            }
                

            if ($('#nombre').val() === "") {
                alert("Ingrese un nombre de categoría");
                return;
            }
                
            $("form").submit();
        });

    });

</script>

admin/QavantWeb/Views/Categorias/Delete.cshtml
@model QavantWeb.Models.Categoria

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Seguro que desea eliminar esta categoría?</h3>
<div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">Datos</h3>
        </div>
        <div class="panel-body">
            <div class="container col-md-12">
                <div class="row">
                    <dl class="dl-horizontal">
                        <dt class="texto-label-left">
                            Nombre
                        </dt>
                        <dd class="texto-label-left">
                            @Html.DisplayFor(model => model.Nombre)
                        </dd>
                        <dt class="texto-label-left">
                            Padre
                        </dt>
                        <dd class="texto-label-left">
                            @Html.DisplayFor(model => model.Categoria1.Nombre)
                        </dd>
                        <dt class="texto-label-left">
                            Módulo
                        </dt>
                        <dd class="texto-label-left">
                            @Html.DisplayFor(model => model.Modulo.Nombre)
                        </dd>
                    </dl>
                </div>
            </div>

            </dl>
        </div>
    </div>



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <a href="@Url.Action("Index", "Categorias", new { id = Model.Id })" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash " aria-hidden="true"></span> Eliminar </button>
    }
</div>

admin/QavantWeb/Views/Categorias/Details.cshtml
@model QavantWeb.Models.Categoria

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Habilitada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habilitada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria1.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria1.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modulo.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modulo.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

admin/QavantWeb/Views/Categorias/Edit.cshtml
@model QavantWeb.Models.Categoria

@{
    ViewBag.Title = "Edit";
}

<h2>Categoría</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Editar</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id, new { id = "hfCategoriaId" })
    @Html.HiddenFor(model => model.EmpresaId)
    @Html.HiddenFor(model => model.ModuloId)
    <div class="form-group">
        <div class="control-label col-md-2"> Módulo</div>
        <div class="col-md-10">
            <select id="modulosDropDownList" class="form-control" name="ModuloId" disabled></select>
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"> Nombre</div>
        <div class="col-md-10">
            <input id="nombre" name="Nombre" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"> Padre</div>
        <div class="col-md-10">
            <select id="categoriasDropDownList" class="form-control" name="PadreCategoriaId"></select>
        </div>
    </div>


    <hr />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("Index", "Categorias", new { id = Model.Id })" class="btn btn-default"><span class="glyphicon glyphicon-menu-left " aria-hidden="true"></span> Volver</a>
            <input type="submit" value="Guardar" class="btn btn-primary" id="cmdSubmit" />
        </div>
    </div>
</div>
}



<script>


    $(document).ready(function () {
        //precargamos formularios
        var pageURL = window.location.href;
        var lastURLSegment = pageURL.substr(pageURL.lastIndexOf('/') + 1);
        var endpoint = '@Url.Action("GetCategoriaById", "Categorias", new { id = "-1" })';
        endpoint = endpoint.replace("-1", lastURLSegment);

        $.ajax({
            type: "GET",
            url: endpoint,
            dataType: "json",
            success: function (data) {
                //populamos nombre de categoria
                $('#nombre').val(data.CategoriaNombre);

                //populamos el combo "modulos"
                $('#modulosDropDownList').html('');
                var optionsModulos = '';
                optionsModulos += '<option value="0">Seleccionar</option>';

                for (var i = 0; i < data.Modulos.length; i++) {
                    if (data.ModuloId == data.Modulos[i].Id) {
                        optionsModulos += '<option selected value="' + data.Modulos[i].Id + '">' + data.Modulos[i].Nombre + '</option>';
                    } else {
                        optionsModulos += '<option value="' + data.Modulos[i].Id + '">' + data.Modulos[i].Nombre + '</option>';
                    }
                }
                $('#modulosDropDownList').append(optionsModulos);

                //populamos el combo "categorias"
                $('#categoriasDropDownList').html('');
                var optionsCategorias = '';
                data.Categorias.push({ Id: 0, Nombre: 'Sin Padre' });
                var editedCategoryId = $("#hfCategoriaId").val();
                for (var i = 0; i < data.Categorias.length; i++) {
                    // No mostramos la categoría actual dentro del combo de categorías. No puede una categoría ser padre de sí misma.
                    if (data.Categorias[i].Id == editedCategoryId)
                        continue;
                    if (data.CategoriaPadreId == data.Categorias[i].Id) {
                        optionsCategorias += '<option selected value="' + data.Categorias[i].Id + '">' + data.Categorias[i].Nombre + '</option>';
                    } else {
                        optionsCategorias += '<option value="' + data.Categorias[i].Id + '">' + data.Categorias[i].Nombre + '</option>';
                    }
                }
                $('#categoriasDropDownList').append(optionsCategorias);
            },
            error: function (error) {
                alert(error.StatusText);
            }
        });

        //populamos combo categorias
        $('#modulosDropDownList').on("change", function () {
            var moduloId = $('#modulosDropDownList').val();
            if (moduloId == 0) {
                $('#categoriasDropDownList').html('');
                return;
            }

            var obj = { moduloId: moduloId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCategoriasByModulo", "Categorias")',
                dataType: "json",
                data: obj,
                success: function (data) {
                    $('#categoriasDropDownList').html('');
                    var options = '';
                    options += '<option value="0">Sin Padre</option>';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i].Id + '">' + data[i].Nombre + '</option>';
                    }
                    $('#categoriasDropDownList').append(options);
                },
                error: function (error) {
                    alert(error.StatusText);
                }
            });
        });


        //validaciones
        $("#cmdSubmit").click(function (event) {
            event.preventDefault();
            if ($('#modulosDropDownList').val() == 0) {
                alert("Seleccione un módulo");
                return;
            }


            if ($('#nombre').val() === "") {
                alert("Ingrese un nombre de categoría");
                return;
            }

            $("form").submit();
        });

    });
</script>

admin/QavantWeb/Views/Categorias/Index.cshtml
@model IEnumerable<QavantWeb.Models.Categoria>

@{
    ViewBag.Title = "Index";
}

<h2>Categorías</h2>
<div style="margin-bottom: 30px">
    <a href="@Url.Action("Create", "Categorias")" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nueva Categoría</a>
    <a href="@Url.Action("IndexDeleted", "Categorias")" class="btn btn-danger"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Categorías Eliminadas</a>
</div>

<table id="CatList" class="table hover display compact stripe">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Módulo
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modulo.Nombre)
            </td>
            <td>
                <a href="@Url.Action("Edit", "Categorias", new { id = item.Id })" class="btn btn-primary"><span class="glyphicon glyphicon-pencil " aria-hidden="true"></span></a>
                <a href="@Url.Action("Delete", "Categorias", new { id = item.Id })" class="btn btn-danger"><span class="glyphicon glyphicon-trash " aria-hidden="true"></span></a>
            </td>
        </tr>
    }

</table>
<script>
    $(document).ready(function () {
        $('#CatList').DataTable({
            "order":[[1,"asc"]],
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por página",
                "zeroRecords": "No se encontraron resultados",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Ningún registro disponible",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar:",
                "processing": "Procesando...",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Siguiente",
                    "previous": "Anterior"
                },
            },
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

admin/QavantWeb/Views/Categorias/IndexDeleted.cshtml
@model IEnumerable<QavantWeb.Models.Categoria>

@{
    ViewBag.Title = "Categorías eliminadas";
}

<h2>Categorías</h2>

<p>
    <a href="@Url.Action("Index", "Categorias")" class="btn btn-default"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Volver a Lista de Categorías</a>
</p>

<table id="CategoriasList" class="table hover display compact stripe">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Padre
            </th>
            <th>
                Módulo
            </th>
            <th></th>
        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria1.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modulo.Nombre)
            </td>
            <td>
                <a href="@Url.Action("Enable", "Categorias", new { id = item.Id })" onclick="javascript: return confirm('¿Confirma que desea activar la categoría nuevamente?');" class="btn btn-success"><span class="glyphicon glyphicon-ok " aria-hidden="true"></span> Activar</a>
            </td>
        </tr>
    }

</table>

<script>
    $(document).ready(function () {
        $('#CategoriasList').DataTable({
            "order": [[1, "desc"]],
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por página",
                "zeroRecords": "No se encontraron resultados",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Ningún registro disponible",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar:",
                "processing": "Procesando...",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Siguiente",
                    "previous": "Anterior"
                },
            },
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>